# Generated by Django 5.2.4 on 2025-08-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainreceiptdocument',
            name='calendar_type',
            field=models.CharField(blank=True, choices=[('gregorian', 'Gregorian (GC)'), ('ethiopian', 'Ethiopian (EC)')], help_text='Was the printed date in Gregorian or Ethiopian calendar?', max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='mainreceiptdocument',
            name='issue_date',
            field=models.DateField(help_text='Date in Gregorian calendar (converted if Ethiopian)'),
        ),
    ]
