# Generated by Django 5.2.4 on 2025-08-15 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mainreceiptdocument_calendar_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainreceiptdocument',
            name='calendar_type',
        ),
        migrations.RemoveField(
            model_name='mainreceiptdocument',
            name='issue_date',
        ),
    ]
