# Generated by Django 5.2.4 on 2025-08-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_mainreceiptdocument_calendar_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='attachement_receipt',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='main_receipt_document',
        ),
        migrations.AddField(
            model_name='withholdingreceiptdocument',
            name='company_tin',
            field=models.CharField(blank=True, help_text='10-digit TIN of the company receiving the withholding receipt', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='withholdingreceiptdocument',
            name='withholding_receipt_number',
            field=models.CharField(help_text='Withholding receipt number from tax authority', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='mainreceiptdocument',
            unique_together={('receipt_number', 'company_tin')},
        ),
        migrations.AlterUniqueTogether(
            name='withholdingreceiptdocument',
            unique_together={('withholding_receipt_number', 'company_tin')},
        ),
    ]
