# Generated by Django 5.2.4 on 2025-08-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_receipt_attachement_receipt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withholdingreceiptdocument',
            name='company_tin',
            field=models.CharField(default=1234567890, help_text='10-digit TIN of the company receiving the withholding receipt', max_length=10),
            preserve_default=False,
        ),
    ]
