# Generated by Django 5.2.4 on 2025-08-19 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_withholdingreceiptdocument_company_tin'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='machine_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
